import { micaBuiltinCommands } from '../index.js';

const command = micaBuiltinCommands.createAgentsCommand({
  showMessage: console.log,
  isAgentRunning: () => false,
  getCurrentAgentSessionId: () => undefined,
  getCurrentAgent: () => undefined,
  getCurrentSessionController: () => undefined,
  listRunningAgents: () => [],
  clearIdleAgents: () => ({ cleared: [], remaining: [] }),
  setPluginStatus: () => undefined,
  clearPluginStatus: () => undefined,
  isAgentBusy: () => false,
  newAgentSession: () => ({
    id: 'example',
    index: 1,
    title: 'Example session',
    cwd: process.cwd(),
    providerId: 'example',
    providerName: 'Example',
    model: 'example-model',
    status: { type: 'idle' },
    current: true,
    startedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }),
  forkCurrentAgent: () => ({
    id: 'fork-example',
    index: 2,
    title: 'Forked example session',
    cwd: process.cwd(),
    providerId: 'example',
    providerName: 'Example',
    model: 'example-model',
    status: { type: 'idle' },
    current: false,
    startedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    sourceWasRunning: false,
  }),
  switchAgentSession: () => ({
    id: 'example',
    index: 1,
    title: 'Example session',
    cwd: process.cwd(),
    providerId: 'example',
    providerName: 'Example',
    model: 'example-model',
    status: { type: 'idle' },
    current: true,
    startedAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }),
  refreshCurrentAgentSessionUi: () => undefined,
  getRewindPreview: () => ({ ok: false, message: 'no checkpoint' }),
  applyRewind: () => ({
    id: 'rewind-example',
    conversationLabel: 'example',
    messageCount: 0,
    fileStateAvailable: true,
    files: [],
  }),
  runExclusiveTask: async (_agent, _options, task) => task(),
  clearUI: () => undefined,
  syncModelDisplay: () => undefined,
  compact: async () => ({
    beforeCount: 4,
    afterCount: 1,
    beforeTokenEstimate: 100,
    afterTokenEstimate: 25,
  }),
});

console.log(`/${command.name}: ${command.description}`);
