/**
 * Mica's UI tokens intentionally use Ink theme keys instead of concrete
 * colours.  `@anthropic/ink` exports theme-aware Text and Box components, so
 * these values are resolved against the active light/dark palette at render
 * time.  Keeping the mapping here gives plugins a stable Mica vocabulary
 * without baking a dark-terminal assumption into every component.
 */
export const themeColors = {
  accent: 'claude',
  primary: 'claude',
  success: 'success',
  error: 'error',
  warning: 'warning',
  info: 'claudeBlue_FOR_SYSTEM_SPINNER',
  cyan: 'cyan_FOR_SUBAGENTS_ONLY',
  dim: 'inactive',
  textSecondary: 'inactive',
  borderInput: 'promptBorder',
  border: 'claudeBlue_FOR_SYSTEM_SPINNER',
  text: 'text',
  muted: 'inactive',
  subtle: 'subtle',
  inactive: 'inactive',
  selection: 'selectionBg',
  surfaceUser: 'userMessageBackground',
  surfaceCommit: 'diffAddedDimmed',
  surfaceConfig: 'memoryBackgroundColor',
  surfaceCompact: 'messageActionsBackground',
  surfaceNotice: 'memoryBackgroundColor',
  surfaceError: 'bashMessageBackgroundColor',
  surfaceSelected: 'messageActionsBackground',
  listRow: 'userMessageBackground',
  listRowAlternate: 'userMessageBackgroundHover',
  listRowSelected: 'messageActionsBackground',
  promptBorder: 'promptBorder',
  promptBorderFocus: 'claude',
  promptBorderCommand: 'claudeBlue_FOR_SYSTEM_SPINNER',
  promptBorderQueue: 'warning',
  promptBorderPlugin: 'permission',
  promptBorderBash: 'bashBorder',
  promptBorderDisabled: 'inactive',
  statusRunning: 'inactive',
  statusInfo: 'claudeBlue_FOR_SYSTEM_SPINNER',
  statusSuccess: 'success',
  statusWarning: 'warning',
  statusError: 'error',
  messageGutter: 'inactive',
  messageAssistant: 'text',
  messageUser: 'text',
  messageCommit: 'diffAddedWord',
  messageConfig: 'success',
  messageCompact: 'warning',
  messageNotice: 'warning',
  messageError: 'error',
  messagePending: 'inactive',
  responseGuide: 'subtle',
  toolDefault: 'inactive',
  toolRead: 'cyan_FOR_SUBAGENTS_ONLY',
  toolWrite: 'orange_FOR_SUBAGENTS_ONLY',
  toolShell: 'green_FOR_SUBAGENTS_ONLY',
  toolNetwork: 'blue_FOR_SUBAGENTS_ONLY',
} as const;
