import type { LucideIcon } from 'lucide-react';
import {
  Blocks,
  Braces,
  Cable,
  Check,
  ChevronDown,
  ChevronRight,
  ContactRound,
  Folder,
  FolderPlus,
  History,
  MoreHorizontal,
  Plus,
  RefreshCw,
  Save,
  Search,
  Send,
  Server,
  Sparkles,
  Trash2,
  X,
} from 'lucide-react';

export const appIcons = {
  config: Braces,
  sessions: History,
  roles: ContactRound,
  mcp: Cable,
  skills: Sparkles,
  plugins: Blocks,
  sync: Server,
  check: Check,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  add: Plus,
  folder: Folder,
  folderPlus: FolderPlus,
  more: MoreHorizontal,
  refresh: RefreshCw,
  save: Save,
  search: Search,
  send: Send,
  trash: Trash2,
  close: X,
} satisfies Record<string, LucideIcon>;
